In [8]:
import pandas as pd
import os 
import glob

In [29]:
path = r'visit_data'
filenames = glob.glob(path + "/*.csv")

dfs = []
for filename in filenames:
    dfs.append(pd.read_csv(filename))

# Concatenate all data into one DataFrame
big_frame = pd.concat(dfs, ignore_index=True)
big_frame

,participant_ID,visit_date,Local Time,t,Rf,VT,VE,IV,VO2,VCO2,...,mark Distance,Phase time,VO2/Kg%Pred,BR,VT/Ti,HRR,PaCO2_e,Dyspnea,SV e,CO e
0,TR000105,20220207,14:35:51,00:00:01,34.48,0.495,17.069,278,633.186579,436.671233,...,0,00:00:00,48,79.1,0.81,NaN,35,NaN,NaN,NaN
1,TR000105,20220207,14:35:54,00:00:04,22.39,0.386,8.642,423,243.632787,161.895202,...,0,00:00:03,18,89.4,0.45,89.0,30,NaN,45.3,3.6
2,TR000105,20220207,14:35:56,00:00:06,31.58,0.215,6.789,155,153.178058,111.653509,...,0,00:00:05,12,91.7,0.26,89.0,24,NaN,30.3,2.4
3,TR000105,20220207,14:35:57,00:00:07,45.11,0.361,16.286,434,490.898195,331.038084,...,0,00:00:06,37,80.1,0.55,91.0,30,NaN,80.6,6.2
4,TR000105,20220207,14:35:59,00:00:09,39.74,0.478,18.993,307,619.037790,425.697689,...,0,00:00:08,46,76.8,0.89,91.0,33,NaN,94.8,7.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47156,TR000109,20220518,NaN,00:42:51,14.78,1.968,29.084,2069,1445.077557,735.174081,...,0,00:19:37,56,79.3,1.21,86.0,32,LEVEL_18,200.9,13.9
47157,TR000109,20220518,NaN,00:42:54,23.81,0.812,19.333,575,645.898690,468.487287,...,0,00:19:40,25,86.3,0.93,86.0,32,LEVEL_18,119.7,8.3
47158,TR000109,20220518,NaN,00:42:58,17.00,0.636,10.810,766,259.265612,204.591295,...,0,00:19:44,10,92.3,0.27,87.0,30,LEVEL_18,58.1,3.9
47159,TR000109,20220518,NaN,00:43:04,12.82,1.106,14.179,1279,441.029677,371.705650,...,0,00:19:50,17,89.9,0.39,88.0,34,LEVEL_18,92.0,6.2
47160,TR000109,20220518,NaN,00:43:08,12.42,0.594,7.379,333,219.458560,180.442652,...,0,00:19:54,8,94.8,0.20,88.0,34,LEVEL_18,50.9,3.4

In [30]:
identifiers = big_frame['participant_ID'].unique().tolist()
identifiers

['TR000105',
 'TR000106',
 'TR000102',
 'TR000100',
 'TR000104',
 'TR000109',
 'TR000107',
 'TR000103',
 'TR000101',
 'TR000110',
 'TR000108']

In [31]:
dataframe_list = []
for id in identifiers:
    dates = big_frame.loc[big_frame['participant_ID'] == id, 'visit_date'].unique().tolist()
    for date in dates:
        # Create a filtered DataFrame for the current id and visit_date
        filtered_df = big_frame[(big_frame['participant_ID'] == id) & (big_frame['visit_date'] == date)]
        
        filtered_df = filtered_df.reset_index(drop=True)
        
        # Dynamically create a variable name for the DataFrame
        variable_name = f"df_{id}_{date}"
        
        # Store the filtered DataFrame in a global variable with the generated name
        globals()[variable_name] = filtered_df

        dataframe_list.append(variable_name)

        #print confirmation
        print(f"Created DataFrame: {variable_name}")
        

dataframe_list

Created DataFrame: df_TR000105_20220207
Created DataFrame: df_TR000105_20220517
Created DataFrame: df_TR000105_20220920
Created DataFrame: df_TR000106_20220420
Created DataFrame: df_TR000106_20220208
Created DataFrame: df_TR000106_20220823
Created DataFrame: df_TR000102_20220204
Created DataFrame: df_TR000102_20220401
Created DataFrame: df_TR000102_20220630
Created DataFrame: df_TR000100_20220623
Created DataFrame: df_TR000100_20220331
Created DataFrame: df_TR000100_20220203
Created DataFrame: df_TR000104_20220627
Created DataFrame: df_TR000104_20220207
Created DataFrame: df_TR000104_20220314
Created DataFrame: df_TR000109_20220209
Created DataFrame: df_TR000109_20220824
Created DataFrame: df_TR000109_20220518
Created DataFrame: df_TR000107_20220519
Created DataFrame: df_TR000107_20220208
Created DataFrame: df_TR000107_20220805
Created DataFrame: df_TR000103_20220401
Created DataFrame: df_TR000103_20220204
Created DataFrame: df_TR000103_20220706
Created DataFrame: df_TR000101_20220203
Created DataFrame: df_TR000101_20220630
Created DataFrame: df_TR000101_20220331
Created DataFrame: df_TR000110_20220210
Created DataFrame: df_TR000110_20220428
Created DataFrame: df_TR000110_20220901
Created DataFrame: df_TR000108_20220209

['df_TR000105_20220207',
 'df_TR000105_20220517',
 'df_TR000105_20220920',
 'df_TR000106_20220420',
 'df_TR000106_20220208',
 'df_TR000106_20220823',
 'df_TR000102_20220204',
 'df_TR000102_20220401',
 'df_TR000102_20220630',
 'df_TR000100_20220623',
 'df_TR000100_20220331',
 'df_TR000100_20220203',
 'df_TR000104_20220627',
 'df_TR000104_20220207',
 'df_TR000104_20220314',
 'df_TR000109_20220209',
 'df_TR000109_20220824',
 'df_TR000109_20220518',
 'df_TR000107_20220519',
 'df_TR000107_20220208',
 'df_TR000107_20220805',
 'df_TR000103_20220401',
 'df_TR000103_20220204',
 'df_TR000103_20220706',
 'df_TR000101_20220203',
 'df_TR000101_20220630',
 'df_TR000101_20220331',
 'df_TR000110_20220210',
 'df_TR000110_20220428',
 'df_TR000110_20220901',
 'df_TR000108_20220209']

In [32]:
df_TR000105_20220207

,participant_ID,visit_date,Local Time,t,Rf,VT,VE,IV,VO2,VCO2,...,mark Distance,Phase time,VO2/Kg%Pred,BR,VT/Ti,HRR,PaCO2_e,Dyspnea,SV e,CO e
0,TR000105,20220207,14:35:51,00:00:01,34.48,0.495,17.069,278,633.186579,436.671233,...,0,00:00:00,48,79.1,0.81,NaN,35,NaN,NaN,NaN
1,TR000105,20220207,14:35:54,00:00:04,22.39,0.386,8.642,423,243.632787,161.895202,...,0,00:00:03,18,89.4,0.45,89.0,30,NaN,45.3,3.6
2,TR000105,20220207,14:35:56,00:00:06,31.58,0.215,6.789,155,153.178058,111.653509,...,0,00:00:05,12,91.7,0.26,89.0,24,NaN,30.3,2.4
3,TR000105,20220207,14:35:57,00:00:07,45.11,0.361,16.286,434,490.898195,331.038084,...,0,00:00:06,37,80.1,0.55,91.0,30,NaN,80.6,6.2
4,TR000105,20220207,14:35:59,00:00:09,39.74,0.478,18.993,307,619.037790,425.697689,...,0,00:00:08,46,76.8,0.89,91.0,33,NaN,94.8,7.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1484,TR000105,20220207,15:24:44,00:48:54,7.63,0.565,4.313,784,161.262790,131.645771,...,0,00:19:51,12,94.7,0.35,70.0,35,LEVEL_19,25.6,2.5
1485,TR000105,20220207,15:24:46,00:48:56,19.35,0.402,7.781,345,233.942437,178.230723,...,0,00:19:53,18,90.5,0.23,70.0,32,LEVEL_19,35.3,3.5
1486,TR000105,20220207,15:24:48,00:48:58,24.90,0.360,8.963,215,262.451382,195.850193,...,0,00:19:55,20,89.0,0.63,70.0,34,LEVEL_19,38.9,3.8
1487,TR000105,20220207,15:24:49,00:48:59,41.38,0.944,39.062,370,1532.565196,1160.836310,...,0,00:19:56,115,52.2,1.57,70.0,38,LEVEL_19,124.5,12.2
1488,TR000105,20220207,15:24:57,00:49:07,10.07,0.506,5.094,846,190.259985,142.724869,...,0,00:20:04,14,93.8,0.58,75.0,34,LEVEL_19,31.1,2.9