**MIPACE Feature Extraction**

In [1]:
import pandas as pd
import os 
import glob

In [2]:
path = r'visit_data'
filenames = glob.glob(path + "/*.csv")

dfs = []
for filename in filenames:
    dfs.append(pd.read_csv(filename))

# Concatenate all data into one DataFrame
big_frame = pd.concat(dfs, ignore_index=True)
big_frame

,participant_ID,visit_date,Local Time,t,Rf,VT,VE,IV,VO2,VCO2,...,mark Distance,Phase time,VO2/Kg%Pred,BR,VT/Ti,HRR,PaCO2_e,Dyspnea,SV e,CO e
0,TR000105,20220207,14:35:51,00:00:01,34.48,0.495,17.069,278,633.186579,436.671233,...,0,00:00:00,48,79.1,0.81,NaN,35,NaN,NaN,NaN
1,TR000105,20220207,14:35:54,00:00:04,22.39,0.386,8.642,423,243.632787,161.895202,...,0,00:00:03,18,89.4,0.45,89.0,30,NaN,45.3,3.6
2,TR000105,20220207,14:35:56,00:00:06,31.58,0.215,6.789,155,153.178058,111.653509,...,0,00:00:05,12,91.7,0.26,89.0,24,NaN,30.3,2.4
3,TR000105,20220207,14:35:57,00:00:07,45.11,0.361,16.286,434,490.898195,331.038084,...,0,00:00:06,37,80.1,0.55,91.0,30,NaN,80.6,6.2
4,TR000105,20220207,14:35:59,00:00:09,39.74,0.478,18.993,307,619.037790,425.697689,...,0,00:00:08,46,76.8,0.89,91.0,33,NaN,94.8,7.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47156,TR000109,20220518,NaN,00:42:51,14.78,1.968,29.084,2069,1445.077557,735.174081,...,0,00:19:37,56,79.3,1.21,86.0,32,LEVEL_18,200.9,13.9
47157,TR000109,20220518,NaN,00:42:54,23.81,0.812,19.333,575,645.898690,468.487287,...,0,00:19:40,25,86.3,0.93,86.0,32,LEVEL_18,119.7,8.3
47158,TR000109,20220518,NaN,00:42:58,17.00,0.636,10.810,766,259.265612,204.591295,...,0,00:19:44,10,92.3,0.27,87.0,30,LEVEL_18,58.1,3.9
47159,TR000109,20220518,NaN,00:43:04,12.82,1.106,14.179,1279,441.029677,371.705650,...,0,00:19:50,17,89.9,0.39,88.0,34,LEVEL_18,92.0,6.2
47160,TR000109,20220518,NaN,00:43:08,12.42,0.594,7.379,333,219.458560,180.442652,...,0,00:19:54,8,94.8,0.20,88.0,34,LEVEL_18,50.9,3.4

In [5]:
#Split Up Dataframes
def create_dataframe_dictionary(parent_df):
    participant_registry = dict()
    for row in parent_df.itertuples():
        participant_registry[row.participant_ID] = dict()
    for row in parent_df.itertuples():
        participant_registry[row.participant_ID][row.visit_date] = []
    for row in parent_df.itertuples():
        participant_registry[row.participant_ID][row.visit_date].append(row)
    participant_df = dict()
    for participant_id, participant_data in participant_registry.items():
        for visit_date in participant_data.keys():
            participant_df[f'{participant_id}_{visit_date}'] = pd.DataFrame(participant_registry[participant_id][visit_date])
    print(participant_df.keys())
    return participant_df

participant_df = create_dataframe_dictionary(big_frame)
participant_df['TR000105_20220207']

dict_keys(['TR000105_20220207', 'TR000105_20220517', 'TR000105_20220920', 'TR000106_20220420', 'TR000106_20220208', 'TR000106_20220823', 'TR000102_20220204', 'TR000102_20220401', 'TR000102_20220630', 'TR000100_20220623', 'TR000100_20220331', 'TR000100_20220203', 'TR000104_20220627', 'TR000104_20220207', 'TR000104_20220314', 'TR000109_20220209', 'TR000109_20220824', 'TR000109_20220518', 'TR000107_20220519', 'TR000107_20220208', 'TR000107_20220805', 'TR000103_20220401', 'TR000103_20220204', 'TR000103_20220706', 'TR000101_20220203', 'TR000101_20220630', 'TR000101_20220331', 'TR000110_20220210', 'TR000110_20220428', 'TR000110_20220901', 'TR000108_20220209'])

,Index,participant_ID,visit_date,_3,t,Rf,VT,VE,IV,VO2,...,_85,_86,_87,BR,_89,HRR,PaCO2_e,Dyspnea,_93,_94
0,0,TR000105,20220207,14:35:51,00:00:01,34.48,0.495,17.069,278,633.186579,...,0,00:00:00,48,79.1,0.81,NaN,35,NaN,NaN,NaN
1,1,TR000105,20220207,14:35:54,00:00:04,22.39,0.386,8.642,423,243.632787,...,0,00:00:03,18,89.4,0.45,89.0,30,NaN,45.3,3.6
2,2,TR000105,20220207,14:35:56,00:00:06,31.58,0.215,6.789,155,153.178058,...,0,00:00:05,12,91.7,0.26,89.0,24,NaN,30.3,2.4
3,3,TR000105,20220207,14:35:57,00:00:07,45.11,0.361,16.286,434,490.898195,...,0,00:00:06,37,80.1,0.55,91.0,30,NaN,80.6,6.2
4,4,TR000105,20220207,14:35:59,00:00:09,39.74,0.478,18.993,307,619.037790,...,0,00:00:08,46,76.8,0.89,91.0,33,NaN,94.8,7.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1484,1484,TR000105,20220207,15:24:44,00:48:54,7.63,0.565,4.313,784,161.262790,...,0,00:19:51,12,94.7,0.35,70.0,35,LEVEL_19,25.6,2.5
1485,1485,TR000105,20220207,15:24:46,00:48:56,19.35,0.402,7.781,345,233.942437,...,0,00:19:53,18,90.5,0.23,70.0,32,LEVEL_19,35.3,3.5
1486,1486,TR000105,20220207,15:24:48,00:48:58,24.90,0.360,8.963,215,262.451382,...,0,00:19:55,20,89.0,0.63,70.0,34,LEVEL_19,38.9,3.8
1487,1487,TR000105,20220207,15:24:49,00:48:59,41.38,0.944,39.062,370,1532.565196,...,0,00:19:56,115,52.2,1.57,70.0,38,LEVEL_19,124.5,12.2
1488,1488,TR000105,20220207,15:24:57,00:49:07,10.07,0.506,5.094,846,190.259985,...,0,00:20:04,14,93.8,0.58,75.0,34,LEVEL_19,31.1,2.9

In [54]:
def test_keys(df_dictionary):
    for key, values in df_dictionary.items():
        for row in values.itertuples():
            assert key == f'{row.participant_ID}_{row.visit_date}'
    return True

test_keys(participant_df)

True

In [52]:
#Create Outcome DF
def create_outcome_df(dictionary_df):
    id_list = list(dictionary_df.keys())
    result_df = pd.DataFrame({
    "participant_visit_id": id_list,
    "VO2_peak": None,
    "VO2/kgPeak": None,
    "True VO2max": None,
    "VO2Peak start time- global": None,
    "VO2Peak end time- global": None,
    "VO2Peak start time- local": None,
    "VO2Peak end time- local": None,
    "RQPeak": None,
    "HRPeak": None,
    "GradePeak": None,
    "SpeedPeak": None,
    "MarkerPeak": None,
    "EEMPeak": None,
    "Fat%Peak": None,
    "CHO%Peak": None,
    "Lactate-VO2Peak": None,
    "RPE-VO2peak": None,
    })

    # Set participant_id as the index
    result_df.set_index("participant_visit_id", inplace=True)
    return result_df
create_outcome_df(participant_df)
outcome_df = create_outcome_df(participant_df)
outcome_df

,VO2_peak,VO2/kgPeak,True VO2max,VO2Peak start time- global,VO2Peak end time- global,VO2Peak start time- local,VO2Peak end time- local,RQPeak,HRPeak,GradePeak,SpeedPeak,MarkerPeak,EEMPeak,Fat%Peak,CHO%Peak,Lactate-VO2Peak,RPE-VO2peak
participant_visit_id,,,,,,,,,,,,,,,,,
TR000105_20220207,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000105_20220517,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000105_20220920,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000106_20220420,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000106_20220208,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000106_20220823,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000102_20220204,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000102_20220401,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000102_20220630,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000100_20220623,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000100_20220331,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000100_20220203,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000104_20220627,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000104_20220207,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000104_20220314,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000109_20220209,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000109_20220824,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000109_20220518,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000107_20220519,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000107_20220208,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000107_20220805,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000103_20220401,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000103_20220204,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000103_20220706,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000101_20220203,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000101_20220630,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000101_20220331,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000110_20220210,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000110_20220428,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000110_20220901,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000108_20220209,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [53]:
#Get VO2 Peak
def get_VO2_peak(df_dictionary,result_df):
    id_list = list(result_df.index)
    for id in id_list:
        VO2_peak = df_dictionary[id]['VO2'].rolling(window=30).mean().max()
        result_df.loc[id]['VO2_peak'] = VO2_peak
    return result_df

outcome_df = get_VO2_peak(participant_df,outcome_df)
outcome_df

,VO2_peak,VO2/kgPeak,True VO2max,VO2Peak start time- global,VO2Peak end time- global,VO2Peak start time- local,VO2Peak end time- local,RQPeak,HRPeak,GradePeak,SpeedPeak,MarkerPeak,EEMPeak,Fat%Peak,CHO%Peak,Lactate-VO2Peak,RPE-VO2peak
participant_visit_id,,,,,,,,,,,,,,,,,
TR000105_20220207,2392.75406,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000105_20220517,2416.686221,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000105_20220920,2409.568712,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000106_20220420,3824.291465,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000106_20220208,3853.939777,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000106_20220823,3571.045272,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000102_20220204,3482.613771,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000102_20220401,3758.891331,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000102_20220630,3765.391967,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000100_20220623,3424.979335,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000100_20220331,3406.137048,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000100_20220203,3103.621538,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000104_20220627,3254.050379,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000104_20220207,3266.88678,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000104_20220314,3312.878399,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000109_20220209,3663.671019,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000109_20220824,3869.816618,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000109_20220518,3334.47512,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000107_20220519,3842.933284,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000107_20220208,4112.720322,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000107_20220805,4211.022027,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000103_20220401,2957.005965,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000103_20220204,3189.608091,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000103_20220706,3002.605597,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000101_20220203,2643.543045,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000101_20220630,2560.66106,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000101_20220331,2648.330287,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000110_20220210,3249.187453,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000110_20220428,3096.577239,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000110_20220901,3177.066873,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000108_20220209,2623.048131,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [60]:

def get_VO2_kg_peak(df_dictionary, result_df):
    for id in list(result_df.index):
        VO2_kg_peak = df_dictionary[id]['_16'].rolling(window=30).mean().max()
        result_df.loc[id]['VO2/kgPeak'] = VO2_kg_peak
    return result_df
outcome_df = get_VO2_kg_peak(participant_df, outcome_df)
outcome_df

,VO2_peak,VO2/kgPeak,True VO2max,VO2Peak start time- global,VO2Peak end time- global,VO2Peak start time- local,VO2Peak end time- local,RQPeak,HRPeak,GradePeak,SpeedPeak,MarkerPeak,EEMPeak,Fat%Peak,CHO%Peak,Lactate-VO2Peak,RPE-VO2peak
participant_visit_id,,,,,,,,,,,,,,,,,
TR000105_20220207,2392.75406,54.257333,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000105_20220517,2416.686221,53.348667,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000105_20220920,2409.568712,53.905,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000106_20220420,3824.291465,55.911,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000106_20220208,3853.939777,54.434,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000106_20220823,3571.045272,52.437667,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000102_20220204,3482.613771,53.332,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000102_20220401,3758.891331,58.367333,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000102_20220630,3765.391967,56.369,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000100_20220623,3424.979335,66.247667,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000100_20220331,3406.137048,66.526667,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000100_20220203,3103.621538,59.571333,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000104_20220627,3254.050379,55.153667,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000104_20220207,3266.88678,56.519,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000104_20220314,3312.878399,56.245333,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000109_20220209,3663.671019,46.611,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000109_20220824,3869.816618,49.235333,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000109_20220518,3334.47512,42.695,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000107_20220519,3842.933284,54.433,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000107_20220208,4112.720322,56.107667,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000107_20220805,4211.022027,59.478333,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000103_20220401,2957.005965,51.248667,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000103_20220204,3189.608091,56.353667,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000103_20220706,3002.605597,51.590667,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000101_20220203,2643.543045,47.375333,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000101_20220630,2560.66106,45.401667,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000101_20220331,2648.330287,47.461,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000110_20220210,3249.187453,48.786333,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000110_20220428,3096.577239,46.426,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000110_20220901,3177.066873,47.067333,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
TR000108_20220209,2623.048131,39.564333,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

Index(['Index', 'participant_ID', 'visit_date', '_3', 't', 'Rf', 'VT', 'VE',
       'IV', 'VO2', 'VCO2', 'RQ', 'O2exp', 'CO2exp', '_14', '_15', '_16',
       'METS', 'HR', '_19', 'FeO2', 'FeCO2', 'FetO2', 'FetCO2', 'FiO2',
       'FiCO2', 'PeO2', 'PeCO2', 'PetO2', 'PetCO2', 'SpO2', 'Grade', 'Speed',
       'Phase', 'Marker', '_35', '_36', '_37', 'PB', 'EEkc', 'EEh', 'EEm',
       'EEtot', 'EEkg', 'PRO', 'Fat', 'CHO', '_47', '_48', '_49', 'npRQ',
       '_51', '_52', '_53', '_54', '_55', '_56', '_57', '_58', '_59', '_60',
       '_61', '_62', '_63', '_64', '_65', '_66', '_67', '_68', '_69', '_70',
       '_71', '_72', '_73', '_74', '_75', '_76', 'Ti', 'Te', 'Ttot', '_80',
       '_81', 'LogVE', '_83', '_84', '_85', '_86', '_87', 'BR', '_89', 'HRR',
       'PaCO2_e', 'Dyspnea', '_93', '_94'],
      dtype='object')

In [67]:
#Create Result Dataframes
def create_results_dictionary(parent_df):
    participant_registry = dict()
    for row in parent_df.itertuples():
        participant_registry[row.participant_ID] = dict()
    for row in parent_df.itertuples():
        participant_registry[row.participant_ID][row.visit_date] = []
    participant_result_df = dict()
    columns = ["V02max", "LT1", "LT2", "VT1", "VT2", "Stage 1", "Stage 2", "Stage 3", "... Stage X"]
    rows = [
        "VO2 (mL/min/kg)",
        "Velocity (km/h)",
        "Grade (%)",
        "Stage (#)",
        "RPE (#)",
        "HR (bpm)",
        "Lactate (mmol/L)",
        "RQ",
        "True VO2max? Y/N",
        "Reach Steady State?",
    ]
    for participant_id, participant_data in participant_registry.items():
        for visit_date in participant_data.keys():
            participant_result_df[f'{participant_id}_{visit_date}'] = pd.DataFrame(columns=columns, index=rows)
    print(participant_df.keys())
    return participant_result_df

participant_result_df = create_results_dictionary(big_frame)
participant_result_df['TR000105_20220207']

dict_keys(['TR000105_20220207', 'TR000105_20220517', 'TR000105_20220920', 'TR000106_20220420', 'TR000106_20220208', 'TR000106_20220823', 'TR000102_20220204', 'TR000102_20220401', 'TR000102_20220630', 'TR000100_20220623', 'TR000100_20220331', 'TR000100_20220203', 'TR000104_20220627', 'TR000104_20220207', 'TR000104_20220314', 'TR000109_20220209', 'TR000109_20220824', 'TR000109_20220518', 'TR000107_20220519', 'TR000107_20220208', 'TR000107_20220805', 'TR000103_20220401', 'TR000103_20220204', 'TR000103_20220706', 'TR000101_20220203', 'TR000101_20220630', 'TR000101_20220331', 'TR000110_20220210', 'TR000110_20220428', 'TR000110_20220901', 'TR000108_20220209'])

,V02max,LT1,LT2,VT1,VT2,Stage 1,Stage 2,Stage 3,... Stage X
VO2 (mL/min/kg),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Velocity (km/h),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Grade (%),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Stage (#),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RPE (#),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HR (bpm),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lactate (mmol/L),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
True VO2max? Y/N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Reach Steady State?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN